# Built-in Functions

Piece of reusable code aimed to solve a particular task

General recipe  --> output = function_name(input)


In [2]:
fam = [1,2]

# call a MAX function
max(fam)


2

In [3]:
# assign result to variable
tallest = max(fam)

In [4]:
round(1.68,1)

1.7

In [85]:
round(1.5)

2

In [6]:
# help will print help contents of a function
help(round)

Help on built-in function round in module builtins:

round(...)
    round(number[, ndigits]) -> number
    
    Round a number to a given precision in decimal digits (default 0 digits).
    This returns an int when called with one argument, otherwise the
    same type as the number. ndigits may be negative.



In [14]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full,reverse=True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


# Methods 

## Methods are functions that belong to Objects

List, String, Float are all examples of object types. You can use methods that are provided by Python on each of the objects.

Use DOT notation to call methods on Objects

## objects of different types can have methods with same name

Example - index() method can be used on String and List

In [15]:
# string to experiment with: room
room = "poolhouse"

# Use upper() on room: room_up
room_up = room.upper()

# Print out room and room_up
print(room)
print(room_up)

# Print out the number of o's in room
print(room.count("o"))

poolhouse
POOLHOUSE
3


In [87]:
# Create list areas
areas = [11.25, 20.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 14.5 appears in areas
print(areas.count(20.0))


1
2


In [21]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)


# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


# Packages

## Directory of Python scripts

### pkg1
    --- module1.py
    --- module2.py

## Each script = module. The modules specify functions, methods and new Python types

### numpy, scikit-learn, matplotlib are all examples of packages

In [24]:
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = 2*math.pi*r

# Calculate A
A = math.pi*r*r

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [26]:
help(math)

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.6/library/math
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(...)
        acos(x)
        
        Return the arc cosine (measured in radians) of x.
    
    acosh(...)
        acosh(x)
        
        Return the inverse hyperbolic cosine of x.
    
    asin(...)
        asin(x)
        
        Return the arc sine (measured in radians) of x.
    
    asinh(...)
        asinh(x)
        
        Return the inverse hyperbolic sine of x.
    
    atan(...)
        atan(x)
        
 

In [90]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon if 12 degrees. Store in dist.
dist = r * radians(12) # 12 degrees 

# arc_length (s) = r * theta

# Print out dist
print(dist)

40317.10572106901


# Numpy 

List can hold many different types. But 1 feature is missing - operations on entire collection of values

Numpy is an alternative to regular Python list - the numpy array

Easy and Fast

In [28]:
import numpy as np

In [29]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [32]:
# height is available as a regular list
height = [1,2,3]

# Import numpy
import numpy as np

# Create a Numpy array from height: np_height
np_height = np.array(height)

# Print out np_height
print(np_height)

# Convert np_height to m: np_height_m
np_height_m = 0.0254*np_height

# Print np_height_m
print(np_height_m)

[1 2 3]
[ 0.0254  0.0508  0.0762]


In [100]:
# access using indexes
x = [4 , 9 , 6, 3, 1]

print(x[1])

import numpy as np
y = np.array(x)
print(y.shape)
print(y[1])

9
(5,)
9


In [96]:
# pick elements from array greater than 5
high = y > 5

print(y[high])

[9 6]


Numpy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.

In [98]:
np.array([1,"1", False])

array(['1', '1', 'False'],
      dtype='<U21')

In [38]:
import numpy as np
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

# 2D arrays

In [42]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball - this means 4 rows and 2 columns
print(np_baseball.shape) # shape is an attribute, hence no parentheses
print(np_baseball)

<class 'numpy.ndarray'>
(4, 2)
[[ 180.    78.4]
 [ 215.   102.7]
 [ 210.    98.5]
 [ 188.    75.2]]


In [106]:
# Access an element in this array using array[r][c] or array[r,c] 
print(np_baseball[1][1])
print(np_baseball[1,1])

102.7
102.7


In [108]:
# get all columns and only 1 row
np_baseball[0,:]

array([ 180. ,   78.4])

In [107]:
# get all rows and only 2nd column
np_baseball[:,1]

array([  78.4,  102.7,   98.5,   75.2])

In [60]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
# r*c = 3*2

In [61]:
print(np_mat)

[[1 2]
 [3 4]
 [5 6]]


In [62]:
# multiply each element by 2
np_mat * 2


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [112]:
# add 2 arrays
np_mat + np.array([10,20]) # r*c = 1*2

array([[11, 22],
       [13, 24],
       [15, 26]])

In [66]:
np.array([10,10]).shape

(2,)

# Basic Statistics

In [72]:
import numpy as np

x = np.array([1,2,3])

In [73]:
np.mean(x)

2.0

In [117]:
np_2d = np.array([[2,-4,3],
                  [3,-6,6]])

In [118]:
# this returns mean of entire array
np.mean(np_2d) # total sum is 21 with 6 elements

0.66666666666666663

In [119]:
# take mean of only 2nd column ( 2 + 5 ) / 2 = 3.5
np.mean(np_2d[:,1])

-5.0

In [120]:
# print correlation between 1st and 2nd column
corr = np.corrcoef(np_2d[:,0],np_2d[:,1])
print("Correlation: " + str(corr))

Correlation: [[ 1. -1.]
 [-1.  1.]]


In [121]:
corr.shape

(2, 2)

In [123]:
help(np.corrcoef)

Help on function corrcoef in module numpy.lib.function_base:

corrcoef(x, y=None, rowvar=True, bias=<class 'numpy._globals._NoValue'>, ddof=<class 'numpy._globals._NoValue'>)
    Return Pearson product-moment correlation coefficients.
    
    Please refer to the documentation for `cov` for more detail.  The
    relationship between the correlation coefficient matrix, `R`, and the
    covariance matrix, `C`, is
    
    .. math:: R_{ij} = \frac{ C_{ij} } { \sqrt{ C_{ii} * C_{jj} } }
    
    The values of `R` are between -1 and 1, inclusive.
    
    Parameters
    ----------
    x : array_like
        A 1-D or 2-D array containing multiple variables and observations.
        Each row of `x` represents a variable, and each column a single
        observation of all those variables. Also see `rowvar` below.
    y : array_like, optional
        An additional set of variables and observations. `y` has the same
        shape as `x`.
    rowvar : bool, optional
        If `rowvar` is True (